#!/bin/bash

outfile=snakefile.scan2_rescue_groups

if [ -f $outfile ]; then
    echo "output file $outfile already exists, please delete it first"
    exit 1
fi


cat > $outfile << EOF
# vim: syntax=python
#
# For the same reason as snakefile.scan2_per_donor, SCAN2 rescue requires
# a module rule for each group.  In short, rescue produces many output
# objects; while these object names are trivial to constuct, it requires
# knowing the rescue group, a wildcard, so it cannot be known in the
# output: section of the rule.
#
# ------------------ THIS FILE IS AUTOMATICALLY GENERATED -------------------
EOF

groups=$(tail -n +2 ../metadata/scan2_rescue_groups.csv | cut -f2 -d, | sort | uniq)
echo "$groups"

for group in $groups; do
    cat >> $outfile << EOF


module scan2_rescue_$group:
    snakefile: "snakefile.scan2"
    config: config

use rule scan2_rescue_run from scan2_rescue_${group} as scan2_rescue_run_${group} with:
    output:
        rdas=protected(expand('scan2/rescue_{{rescue_group}}/objects/{sample}_scan2_object_rescue.rda',
            sample=config['scan2_rescue_groups']['${group}'].values()))

EOF
done >> $outfile
